language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y debhelper fakeroot libncurses5-dev libncursesw5-dev
  
script: ./configure && make && make -C tests && make -C tests run && git clean -df && dpkg-buildpackage -b -us -uc
